name: Nexus Light Node

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # auto restart tiap 6 jam

jobs:
  run-nexus:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Nexus CLI
      run: |
        echo "Y" | curl -L https://cli.nexus.xyz/ | sh
        echo "$HOME/.nexus/bin" >> $GITHUB_PATH

    - name: Run Nexus Light Node
      run: |
        nexus-network start --node-id 35143021
