name: Nexus Light Node

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # auto restart tiap 6 jam

jobs:
  run-nexus:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Debug environment
      run: |
        echo "=== Environment Info ==="
        uname -a
        lsb_release -a || true
        echo "HOME: $HOME"
        echo "PATH: $PATH"

    - name: Install Nexus CLI
      run: |
        echo "Y" | curl -L https://cli.nexus.xyz/ | sh
        ls -lah $HOME/.nexus || true
        ls -lah $HOME/.nexus/bin || true
        echo "$HOME/.nexus/bin" >> $GITHUB_PATH

    - name: Test Nexus CLI
      run: |
        which nexus-network || echo "nexus-network not found"
        nexus-network --help || echo "failed to run nexus-network"

    - name: Run Nexus Light Node
      run: |
        nexus-network start --node-id 35143021
